config/routes.rb
Rails.application.routes.draw do

root 'access#index'
  resources :users
  resources :projects
  resources :panels

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/panel.rb
class Panel < ActiveRecord::Base

belongs_to :project
acts_as_list :scope => :project

scope :sorted, lambda { order("panels.position ASC")}

validates_presence_of :panel_name
validates_length_of :panel_name, :maximum => 50
validates_uniqueness_of :panel_name, :scope => :project_id
validates_presence_of :wire_length
validates_presence_of :runs
validates_presence_of :wire_type
validates_presence_of :conduit_type
validates_presence_of :run_type

end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  before_action :get_project
  before_action :get_user
  before_action :confirm_logged_in
  before_action :set_panel, only: [:show, :edit, :update, :destroy]


  # GET /panels
  # GET /panels.json
  def index
    @panels = @project.panels.sorted

    @panels.each do |panel|
    if Panel.where(:fed_from => panel.panel_name).pluck(:panel_name).length > 0
    @panel_del = "Will also destroy #{Panel.where(:fed_from => panel.panel_name).pluck(:panel_name).join(', ')}"
    else
      @panel_del = "This will delete #{panel.panel_name}"
    end
      panel.c_value = c_val_picker(panel.wire_size, panel.wire_type, 
      panel.conduit_type, panel.run_type)
      if panel.init_fault == nil || panel.init_fault != @project.init_fault
        panel.init_fault = init_fault_picker(panel.fed_from)
      end
      if panel.final_value != nil
        if panel.voltage == 208 || panel.voltage == 480
          panel.f_value = (1.73 * panel.wire_length * init_fault_picker(panel.fed_from))/
          (panel.runs * panel.c_value * panel.voltage)
          panel.m_value = 1/(1+panel.f_value)
          panel.final_value = panel.init_fault * panel.m_value
        else
          panel.f_value = (2 * panel.wire_length * panel.init_fault)/
          (panel.runs * panel.c_value * panel.voltage)
          panel.m_value = 1/(1+panel.f_value)
          panel.final_value = init_fault_picker(panel.fed_from) * panel.m_value
        end
      end
    end
  end

  # GET /panels/1
  # GET /panels/1.json
  def show
      @panel.init_fault = init_fault_picker(@panel.fed_from)
      @panel.c_value = c_val_picker(@panel.wire_size, @panel.wire_type, 
          @panel.conduit_type, @panel.run_type)
        if @panel.voltage == 208 || @panel.voltage == 480
          panel_calcs(1.73)
        else
          panel_calcs(2)
        end
  end

  # GET /panels/new
  def new
    @panel = Panel.new({:project_id => @project.id})
    @panel_count = Panel.count + 1
    @panel_names = Panel.where(:project_id => @project.id).pluck(:panel_name)
    @panel_names.insert(0, "Transformer")
  end

  # GET /panels/1/edit
  def edit
    @panel_count = Panel.count
    @panel_names = Panel.where(:project_id => @panel.project_id).pluck(:panel_name)
    @panel_names.insert(0, "Transformer")
  end

  # POST /panels
  # POST /panels.json
  def create
    @panel = Panel.new(panel_params)
    @panel_count = Panel.count
     @panel_names = Panel.where(:project_id => @panel.project_id).pluck(:panel_name)
    @panel.c_value = c_val_picker(@panel.wire_size, @panel.wire_type, 
          @panel.conduit_type, @panel.run_type)
    respond_to do |format|
      if @panel.save
        format.html { redirect_to @panel, notice: 'Panel was successfully created.'}
        format.json { render :show, status: :created, location: @panel }
      else
        format.html { render :new }
        format.json { render json: @panel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /panels/1
  # PATCH/PUT /panels/1.json
  def update

    respond_to do |format|

      if @panel.update(panel_params)
          @panel.c_value = c_val_picker(@panel.wire_size, @panel.wire_type, 
          @panel.conduit_type, @panel.run_type)
        format.html { redirect_to @panel, notice: 'Panel was successfully updated.' }
        format.json { render :show, status: :ok, location: @panel }
      else
        format.html { render :edit }
        format.json { render json: @panel.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
  end
  # DELETE /panels/1
  # DELETE /panels/1.json
  def destroy
    @panel.destroy
    Panel.where(:fed_from => @panel.panel_name).destroy(Panel.where(:fed_from => @panel.panel_name).pluck(:id))
    flash[:notice] = "Panel '#{@panel.panel_name}' has been destroyed successfully"
    redirect_to(:action => 'index', :project_id => @panel.project_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel
      @panel = Panel.find(params[:id])
    end

    def panel_calcs(var_volt)
      @panel.f_value = (var_volt * @panel.wire_length * init_fault_picker(@panel.fed_from))/
      (@panel.runs * @panel.c_value * @panel.voltage)
      @panel.m_value = 1/(1+@panel.f_value)
      @panel.final_value = init_fault_picker(@panel.fed_from) * @panel.m_value
      @panel.save
    end

    def init_fault_picker(fed_from)
        if fed_from != "Transformer"
          if defined? @project.id
            return Panel.where(:panel_name => fed_from, :project_id => @project.id).pluck(:final_value)[0]
          else
            return Panel.where(:panel_name => fed_from, :project_id => @panel.project_id).pluck(:final_value)[0]
          end
        else
          if defined? @panel
            return Project.where(:id => @panel.project_id).pluck(:init_fault)[0]
          else
            return Project.where(:id => @project.id).pluck(:init_fault)[0]
          end
        end
    end

    def c_val_picker(wire_size, wire_type, conduit_type, runs_type)
      case wire_size
      when "14"
          if wire_type == 1 && conduit_type == 1 && runs_type == 1
            return 389
            elsif wire_type == 1 && conduit_type == 1 && runs_type == 2
              return 389
            elsif wire_type == 1 && conduit_type == 2 && runs_type == 1
              return 389
            elsif wire_type == 1 && conduit_type == 2 && runs_type == 2
              return 389
            elsif wire_type == 2 && conduit_type == 1 && runs_type == 1
              return 237
            elsif wire_type == 2 && conduit_type == 1 && runs_type == 2
              return 237
            elsif wire_type == 2 && conduit_type == 2 && runs_type == 1
              return 237
            elsif wire_type == 2 && conduit_type == 2 && runs_type == 2
              return 237
            end
          when "12"
           if wire_type == 1 && conduit_type == 1 && runs_type == 1
            return 617
          elsif wire_type == 1 && conduit_type == 1 && runs_type == 2
            return 617
          elsif wire_type == 1 && conduit_type == 2 && runs_type == 1
            return 617
          elsif wire_type == 1 && conduit_type == 2 && runs_type == 2
            return 617
          elsif wire_type == 2 && conduit_type == 1 && runs_type == 1
            return 376
          elsif wire_type == 2 && conduit_type == 1 && runs_type == 2
            return 376
          elsif wire_type == 2 && conduit_type == 2 && runs_type == 1
            return 376
          elsif wire_type == 2 && conduit_type == 2 && runs_type == 2
            return 376
          end
        when "10"
         if wire_type == 1 && conduit_type == 1 && runs_type == 1
          return 981
        elsif wire_type == 1 && conduit_type == 1 && runs_type == 2
          return 982
        elsif wire_type == 1 && conduit_type == 2 && runs_type == 1
          return 982
        elsif wire_type == 1 && conduit_type == 2 && runs_type == 2
          return 982
        elsif wire_type == 2 && conduit_type == 1 && runs_type == 1
          return 599
        elsif wire_type == 2 && conduit_type == 1 && runs_type == 2
          return 599
        elsif wire_type == 2 && conduit_type == 2 && runs_type == 1
          return 599
        elsif wire_type == 2 && conduit_type == 2 && runs_type == 2
          return 599
        end
      when "8"
       if wire_type == 1 && conduit_type == 1 && runs_type == 1
        return 1557
      elsif wire_type == 1 && conduit_type == 1 && runs_type == 2
        return 1559
      elsif wire_type == 1 && conduit_type == 2 && runs_type == 1
        return 1559
      elsif wire_type == 1 && conduit_type == 2 && runs_type == 2
        return 1560
      elsif wire_type == 2 && conduit_type == 1 && runs_type == 1
        return 951
      elsif wire_type == 2 && conduit_type == 1 && runs_type == 2
        return 952
      elsif wire_type == 2 && conduit_type == 2 && runs_type == 1
        return 952
      elsif wire_type == 2 && conduit_type == 2 && runs_type == 2
        return 952
      end
    when "6"
     if wire_type == 1 && conduit_type == 1 && runs_type == 1
      return 2425
    elsif wire_type == 1 && conduit_type == 1 && runs_type == 2
      return 2431
    elsif wire_type == 1 && conduit_type == 2 && runs_type == 1
      return 2430
    elsif wire_type == 1 && conduit_type == 2 && runs_type == 2
      return 2433
    elsif wire_type == 2 && conduit_type == 1 && runs_type == 1
      return 1481
    elsif wire_type == 2 && conduit_type == 1 && runs_type == 2
      return 1482
    elsif wire_type == 2 && conduit_type == 2 && runs_type == 1
      return 1482
    elsif wire_type == 2 && conduit_type == 2 && runs_type == 2
      return 1482
    end
    when "4"
     if wire_type == 1 && conduit_type == 1 && runs_type == 1
      return 3806
    elsif wire_type == 1 && conduit_type == 1 && runs_type == 2
      return 3830
    elsif wire_type == 1 && conduit_type == 2 && runs_type == 1
      return 3826
    elsif wire_type == 1 && conduit_type == 2 && runs_type == 2
      return 3838
    elsif wire_type == 2 && conduit_type == 1 && runs_type == 1
      return 2346
    elsif wire_type == 2 && conduit_type == 1 && runs_type == 2
      return 2351
    elsif wire_type == 2 && conduit_type == 2 && runs_type == 1
      return 2350
    elsif wire_type == 2 && conduit_type == 2 && runs_type == 2
      return 2353
    end
    when "3"
     if wire_type == 1 && conduit_type == 1 && runs_type == 1
      return 4774
    elsif wire_type == 1 && conduit_type == 1 && runs_type == 2
      return 4820
    elsif wire_type == 1 && conduit_type == 2 && runs_type == 1
      return 4811
    elsif wire_type == 1 && conduit_type == 2 && runs_type == 2
      return 4833
    elsif wire_type == 2 && conduit_type == 1 && runs_type == 1
      return 2952
    elsif wire_type == 2 && conduit_type == 1 && runs_type == 2
      return 2963

app/helpers/panels_helper.rb
module PanelsHelper

def destroy_link_to(path, options)
  link_to t('.destroy'), path, 
    :method => :delete,
    :class => "btn",
    :confirm => t('.destroy_confirm.body', :item => options[:item]),
    "data-confirm-fade" => true,
    "data-confirm-title" => t('.destroy_confirm.title', :item => options[:item]),
    "data-confirm-cancel" => t('.destroy_confirm.cancel', :item => options[:item]),
    "data-confirm-cancel-class" => ("btn-cancel"),
    "data-confirm-proceed" => t('.destroy_confirm.proceed', :item => options[:item]),
    "data-confirm-proceed-class" => "btn-danger"
end

end

app/views/panels/_form.html.erb
<%= form_for @panel, :html => {:class => "form-horizontal center"} do |f| %>
  <% if @panel.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@panel.errors.count, "error") %> prohibited this panel from being saved:</h2>

      <ul>
      <% @panel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-3">
  <div class="form-group">
    <%= f.label :panel_name %><br>
    <%= f.text_field :panel_name, :size => 40 %>
  </div>
  <div class="form-group">
    <%= f.label :wire_length %><br>
    <%= f.text_field :wire_length %>
  </div>
  <div class="form-group">
    <%= f.label :fed_from %><br>
    <%= f.select :fed_from, @panel_names %>
  </div>

  <div class="form-group">
    <%= f.label :runs %><br>
    <%= f.text_field :runs %>
  </div>
  <div class="form-group">
    <%= f.label :voltage %><br>
    <%= f.select :voltage, [208, 240, 480], {}, {class: "form-control"} %>
  </div>
    <div class="form-group">
    <%= f.label :wire_size %><br>
    <%= f.select :wire_size, ["14", "12", "10", "8", "6", "4", "3", "2", "1", 
      "1/0", "2/0", "3/0", "4/0", "250", "300", "350", "400", "500", "600", 
      "750", "1,000"], {}, {class: "form-control"} %>
  </div>
  </div>
</div>
    <div class="row">
      <div class="col-sm-2">
        <div class="form-group">
            <%= f.label :wire_type, "Copper", :value => 1 %><br>
           <%= f.radio_button :wire_type, 1,  {class: "form-control"} %>
            <%= f.label :wire_type, "Aluminum", :value => 2 %><br>
            <%= f.radio_button :wire_type, 2, {class: "form-control"} %>
        </div>
      </div>
      <div class="col-sm-2">
        <div class="form-group">
            <%= f.label :conduit_type, "Magnetic", :value => 1 %><br>
           <%= f.radio_button :conduit_type, 1,  {class: "form-control"} %>
            <%= f.label :conduit_type, "Non-Magnetic", :value => 2 %><br>
            <%= f.radio_button :conduit_type, 2, {class: "form-control"} %>
      </div>
  </div>
      <div class="col-sm-3">
        <div class="form-group">
            <%= f.label :run_type, "Three Single Conductors", :value => 1 %><br>
           <%= f.radio_button :run_type, 1,  {class: "form-control"} %>
            <%= f.label :run_type, "Three Conductor Cable", :value => 2 %><br>
            <%= f.radio_button :run_type, 2, {class: "form-control"} %>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
        <div class="form-group">
            <%= f.label :position %><br>
           <%= f.select :position, 1..@panel_count, {}, {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.hidden_field :project_id, :value => @panel.project_id %>
          <%= f.submit 'Submit', {:class => 'btn btn-md btn-success'} %>       
          <%= link_to "Back to Panels", {controller: "panels", action: "index",
            project_id: @panel.project_id}, class: "btn btn-md btn-default" %>
        </div>

    </div>
  </div>
</div>
<% end %>

app/views/panels/edit.html.erb
<% @page_title = "Edit Panel" %>

    <h1><%= @page_title %></h1>
  </div>
</div>
</div>

<%= render 'form' %>

app/views/panels/index.html.erb
<% @page_title = "Panels Index" %>


<h1><%= @page_title %></h1>
</div>
</div>
</div>
<div class="container">
  <%= link_to "New Panel", {action: "new", project_id: @project.id}, class: "btn btn-md btn-success" %>
  <%= link_to "Back to Projects", {controller: "projects", action: "index",
   user_id: @project.user_id}, class: "btn btn-md btn-default" %>
 </div>
 <div class="container">
  <div class="row">
    <div class="col-sm-11">
      <h2>Panel Values</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Order</th>
            <th>Panel Name</th>
            <th>Wire length</th>
            <th>Init fault</th>
            <th>Runs</th>
            <th>Voltage</th>
            <th>C value</th>
            <th>Wire Size</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @panels.each do |panel| %>
          <tr>
            <td><%= panel.position %></td>
            <td><%= panel.panel_name %></td>
            <td><%= "#{panel.wire_length.to_i}'" %></td>
            <td><%= number_with_precision(panel.init_fault, precision: 2) %></td>
            <td><%= panel.runs.to_i %></td>
            <td><%= panel.voltage.to_i %></td>
            <td><%= panel.c_value.to_i %></td>
            <td><%= "##{panel.wire_size}" %></td>
            <td><%= link_to 'Show', panel, class: "btn btn-md btn-info" %></td>
            <td><%= link_to 'Edit', edit_panel_path(panel), class: "btn btn-md btn-info" %></td>
            <td><%= link_to 'Destroy', panel, method: :delete, data: { confirm: "Will destroy: #{panel.panel_name} | #{Panel.where(:fed_from => panel.panel_name).pluck(:panel_name).join(', ')}. Are you sure?"}, class: "btn btn-md btn-info" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
      <% if !flash[:notice].blank? %>
    <div class="alert alert-danger fade in">
      <%= flash[:notice] %>
    </div>
    <% end %>
  <div class="row">
    <div class="col-sm-7">
      <h2>Results</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Panel Name</th>
            <th>F Value</th>
            <th>M Value</th>
            <th>Final Value</th>
          </tr>
        </thead>

        <tbody>
          <% @panels.each do |panel| %>
          <tr>
            <td><%= panel.panel_name %></td>
            <td><%= number_with_precision(panel.f_value, precision: 2) %></td>
            <td><%= number_with_precision(panel.m_value, precision: 2) %></td>
            <td><%= number_with_precision(panel.final_value, precision: 2) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>

app/views/panels/new.html.erb
<% @page_title = "New Panel" %>

    <h1><%= @page_title %></h1>
	</div>
</div>
</div>
<%= render 'form' %>

app/views/panels/show.html.erb
<% @page_title = "Panel Details" %>

    <h1><%= @page_title %></h1>
  </div>
</div>
</div>
      <% if !flash[:notice].blank? %>
    <div class="alert alert-danger fade in">
      <%= flash[:notice] %>
    </div>
    <% end %>
<div class="container">
<p>
  <strong>Panel Name:</strong>
  <%= @panel.panel_name %>
</p>

<p>
  <strong>Wire length:</strong>
  <%= @panel.wire_length %>
</p>

<p>
  <strong>Init fault:</strong>
  <%= number_with_precision(@panel.init_fault, precision: 2) %>
</p>

<p>
  <strong>Runs:</strong>
  <%= @panel.runs %>
</p>

<p>
  <strong>Voltage:</strong>
  <%= @panel.voltage %>
</p>

<p>
  <strong>C value:</strong>
  <%= @panel.c_value %>
</p>

<p>
  <strong>Wire Size:</strong>
  <%= @panel.wire_size %>
</p>

<p>
  <strong>Wire Type:</strong>
  <% if @panel.wire_type == 1 %>
    <%= "Copper" %>
    <% else %>
      <%= "Aluminum" %>
  <% end %>
</p>
  <strong>Conduit Type:</strong>
  <% if @panel.wire_type == 1 %>
    <%= "Magnetic" %>
    <% else %>
      <%= "Non-Magnetic" %>
  <% end %>
</p>
  <strong>Type of Run:</strong>
  <% if @panel.wire_type == 1 %>
    <%= "Three Single Conductors" %>
    <% else %>
      <%= "Three Conductor Cable" %>
  <% end %>
</p>
<%= link_to 'Edit', edit_panel_path(@panel), class: "btn btn-md btn-success" %>    
<%= link_to "Back to Panels", {controller: "panels", action: "index",
 project_id: @panel.project_id}, class: "btn btn-md btn-default" %>
 </div>