config/routes.rb
Rails.application.routes.draw do

root 'access#index'
  resources :users
  resources :projects
  resources :panels

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base

has_secure_password

validates_presence_of :user_name
validates_length_of :user_name, :maximum => 15
validates_uniqueness_of :user_name
validates_presence_of :email
validates_uniqueness_of :email
validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

has_many :projects, :dependent => :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :confirm_logged_in, except: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
    flash[:notice] = "User #{@user.user_name} has been created successfully"
    redirect_to(:controller => 'projects', :action => 'index', :user_id => @user.id)
      else
        respond_to do |format|
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :password_digest, :password, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being created:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :user_name %><br>
        <%= f.text_field :user_name %>
      </div>
      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div class="form-group">
        <%= f.submit 'Submit', {:class => 'btn btn-md btn-success'} %>
      </div>
    </div>
  </div>
</div>
 <% end %>

app/views/users/edit.html.erb
<% @page_title = "Edit User" %>

    <h1><%= @page_title %></h1>
  </div>
</div>
</div>
<%= render 'form' %>

app/views/users/index.html.erb
<p class="notice"><%= notice %></p>

<% @page_title = "User Index" %>

    <h1><%= @page_title %></h1>
  </div>
</div>
</div>
<div class="container">
<%= link_to "New User", {action: "new"}, class: "btn btn-md btn-success" %>
<%= link_to "Back to Admin", {controller: "access", action: "index"}, class: "btn btn-md btn-default" %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
<table class="table table-hover">
  <thead>
    <tr>
      <th>User name</th>
      <th>Projects</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.projects.count %></td>
        <td><%= link_to 'View Projects', projects_path(:user_id => user.id), class: "btn btn-md btn-primary"  %></td>
        <td><%= link_to 'Show', user, class: "btn btn-md btn-info" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-md btn-info" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-md btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% @page_title = "Register User" %>

    <h1><%= @page_title %></h1>
	</div>
</div>
</div>
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% @page_title = "User Details" %>

    <h1><%= @page_title %></h1>
  </div>
</div>
</div>
<div class="container">
<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>
<p>
  <strong>Email Address:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-md btn-success" %> 
<%= link_to 'Back', users_path, class: "btn btn-md btn-default" %>
</div>