config/routes.rb
Rails.application.routes.draw do

root 'access#index'
  resources :users
  resources :projects
  resources :panels

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/project.rb
class Project < ActiveRecord::Base

belongs_to :user	
has_many :panels, :dependent => :destroy
acts_as_list :scope => :user

scope :sorted, lambda { order("projects.position ASC")}

validates_presence_of :name
validates_length_of :name, :maximum => 50
validates_length_of :notes, :maximum => 255
validates_uniqueness_of :name, :scope => :user_id

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :confirm_logged_in
  before_action :get_user

  # GET /projects
  # GET /projects.json
  def index
    @projects = @user.projects.sorted
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new({:user_id => @user.id})
    @project_count = Project.count + 1
  end

  # GET /projects/1/edit
  def edit
    @project_count = Project.count
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project_count = Project.count

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    flash[:notice] = "Project '#{@project.name}' has been destroyed successfully"
    redirect_to(:action => 'index', :user_id => @project.user_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :notes, :user_id, :init_fault)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <%= f.label :notes %><br>
        <%= f.text_area(:notes, :size => "40x5") %>
      </div>
      <div class="form-group">
        <%= f.label "Fault at Transformer" %><br>
        <%= f.text_field :init_fault %>
      </div>
    </div>
  </div>
  <div class="row">
      <div class="col-sm-4">
      <div class="form-group">
        <%= f.hidden_field :user_id, :value => @project.user_id %>
      </div>
      <div class="form-group">
        <%= f.label :position %><br>
       <%= f.select :position, 1..@project_count, {}, {class: "form-control"}  %>
      </div>
      <div class="form-group">
        <%= f.submit 'Submit', {:class => 'btn btn-md btn-success'} %> <%= link_to "Back to Projects", {controller: "projects", action: "index",
 user_id: @project.user_id}, class: "btn btn-md btn-default" %>
            </div>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% @page_title = "Edit Project" %>

    <h1><%= @page_title %></h1>
  </div>
</div>
</div>
<%= render 'form' %>

app/views/projects/index.html.erb
<% @page_title = "Project Index" %>



<h1><%= @page_title %></h1>
</div>
</div>
</div>
<div class="container">
  <%= link_to "New Project", {action: "new", user_id: @user.id}, class: "btn btn-md btn-success" %>
  <%= link_to "Back to Admin", {controller: "access", action: "index",
   user_id: @user.id}, class: "btn btn-md btn-default" %>
 </div>

 <div class="container">
  <div class="row">
    <div class="col-sm-11">
      <table class="table table-hover">
        <thead>
          <tr>
            <th data-field="name">Name</th>
            <th>Notes</th>
            <th>Panels</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @projects.each do |project| %>
          <tr>
            <td width="200"><%= project.name %></td>
            <td><%= project.notes %></td>
            <td><%= project.panels.count %>
              <td><%= link_to 'View Panels', panels_path(:project_id => project.id, :user_id => project.user.id), 
              class: "btn btn-md btn-primary" %></td>
              <td><%= link_to 'Show', project, class: "btn btn-md btn-info" %></td>
              <td><%= link_to 'Edit', edit_project_path(project), class: "btn btn-md btn-info" %></td>
              <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-md btn-info" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <% if !flash[:notice].blank? %>
        <div class="alert alert-danger fade in">
          <%= flash[:notice] %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <br>

app/views/projects/new.html.erb
<% @page_title = "New Project" %>

    <h1><%= @page_title %></h1>
	</div>
</div>
</div>
<%= render 'form' %>

app/views/projects/show.html.erb
								<% if !flash[:notice].blank? %>
								<div class="alert alert-danger fade in">
									<%= flash[:notice] %>
								</div>
								<% end %>
								<% @page_title = "Project Details" %>

								<h1><%= @page_title %></h1>
							</div>
						</div>
					</div>
					<div class="container">
						<p>
							<strong>Name:</strong>
							<%= @project.name %>
						</p>

						<p>
							<strong>Notes:</strong>
							<%= @project.notes %>
						</p>

						<%= link_to 'Edit', edit_project_path(@project), class: "btn btn-md btn-success" %> 
						<%= link_to "Back to Projects", {:action => 'index', :user_id => @project.user_id}, class: "btn btn-md btn-default" %>
					</div>